### PR TITLE
Fix pattern errors in windows

### LINKED ISSUE #91: Runtime errors using stack and ghc-8.6.4/ghc-8.4.4 on windows
Error running the test suite with stack and ghc-8.6.4

Catched in the test suite of haskell-ide-engine: https://dev.azure.com/jneira/haskell-ide-engine/_build/results?buildId=434
With other ghc versions it works fine.
Maybe it can affect the normal use of hie (pending of testing)
Error:
```
src\CabalHelper\Compiletime\CompPrograms.hs:95:5: 
  1) CabalHelper, cabal-helper spec, cradle discovery, dummy filepath, finds none-cradle, stack repo, dummy filepath
       uncaught exception: IOException of type UserError
       user error (Pattern match failure in do expression at src\CabalHelper\Compiletime\CompPrograms.hs:95:5-17)
```

https://github.com/DanielG/cabal-helper/blob/1c0f2e8c403126acecfd6d6cccf2ad0b20f38929/src/CabalHelper/Compiletime/CompPrograms.hs#L92-L99

### PR DESCRIPTION
**Pull request by jneira**
* Detected in the azure ci of haskell-ide-engine
* I am pretty sure one of the errors (in `createProgSymlink`) is fixed:
  * azure runs windows+stack+ghc-8.6.4 with failing tests using cabal-helper master: 
     * https://dev.azure.com/jneira/haskell-ide-engine/_build/results?buildId=590&view=results
     * https://dev.azure.com/jneira/haskell-ide-engine/_build/results?buildId=595&view=results
     * and finally https://dev.azure.com/jneira/haskell-ide-engine/_build/results?buildId=601&view=results
  * azure runs using this patch with the test suite green
     * https://dev.azure.com/jneira/haskell-ide-engine/_build/results?buildId=600&view=results
     * https://dev.azure.com/jneira/haskell-ide-engine/_build/results?buildId=589&view=results
  * It reuses an existing fallback that seems to work in the missing pattern case
* The other one (`Stack.paths`) is intermittent and this patch *does not* fix it, only move it up. I think it should be handle there. However it removes the missing pattern and makes it a little bit more resilient against `stack path` format changes. I think the error is triggered cause the `stack path` output is an error but i am not able to replicate it in local.

* I've added `-fwarn-incomplete-uni-patterns` to cabal config but maybe you are fine without them, i will remove in that case
* Fixes #91

### CODE REVIEW

**Comment by jneira** [comment]
The errors calling `stack path` had been:
```
Failures:

  src\CabalHelper\Compiletime\Program\Stack.hs:88:19: 
  1) CabalHelper, cabal-helper spec, cradle discovery, dummy filepath, finds none-cradle, stack repo, dummy filepath
       uncaught exception: PatternMatchFail
       src\CabalHelper\Compiletime\Program\Stack.hs:88:19-59: Irrefutable pattern failed for pattern (key,
                                                              ' ' : val)
```
This one (you can see it [here](https://dev.azure.com/jneira/haskell-ide-engine/_build/results?buildId=590&view=logs&j=067c8a80-91a8-50fe-439e-a8809ddb7afe&t=efa6bc94-8e3a-5312-8566-77f42cbfa530)) is fixed by the patch.
The other one i've seen with this patch applied is:
```
1) CabalHelper, cabal-helper spec, cradle discovery and loading, dummy filepath, finds none-cradle, stack repo
       uncaught exception: IOException of type OtherError
       readCreateProcess: stack "path" "--stack-yaml=D:\\a\\1\\s\\test\\testdata\\cabal-helper\\simple-stack\\stack.yaml" (exit 1): failed
```
Unfortunately the error is not very specific

File: src/CabalHelper/Compiletime/CompPrograms.hs [hunk 1]
```diff
@@ -92,8 +92,11 @@ patchBuildToolProgs SStack progs = do
 createProgSymlink :: FilePath -> FilePath -> IO ()
 createProgSymlink bindir target
   | [exe] <- splitPath target = do
-    Just exe_path <- findExecutable exe
-    createSymbolicLink exe_path (bindir </> takeFileName target)
-  | otherwise = do
-    cwd <- getCurrentDirectory
-    createSymbolicLink (cwd </> target) (bindir </> takeFileName target)
+    mb_exe_path <- findExecutable exe
```
Comment (fendor) [inline src/CabalHelper/Compiletime/CompPrograms.hs:97]: This could also be written as:
```suggestion
    | [exe] <- splitPath target
    , Just exe_path <- findExecutable exe = do
```
to avoid additional case expression

Comment (jneira) [reply src/CabalHelper/Compiletime/CompPrograms.hs:97]: Mmm, and remove Nothing, right?

Comment (jneira) [reply src/CabalHelper/Compiletime/CompPrograms.hs:97]: Maybe you cant use IO in pattern guards? Or i am missing something?

```haskell
createProgSymlink :: FilePath -> FilePath -> IO ()
createProgSymlink bindir target
  | [exe] <- splitPath target
  , Just exe_path <- findExecutable exe = do
      createSymbolicLink exe_path (bindir </> takeFileName target)
  | otherwise = createSymLinkFromCwd
  where createSymLinkFromCwd = do
          cwd <- getCurrentDirectory
          createSymbolicLink (cwd </> target) (bindir </> takeFileName target)
```
throws
```
* Couldn't match expected type `IO (Maybe FilePath)'
              with actual type `Maybe FilePath'
* In the pattern: Just exe_path
  In a stmt of a pattern guard for
                 an equation for `createProgSymlink':
    Just exe_path <- findExecutable exe
  In an equation for `createProgSymlink':
.....
```

Comment (fendor) [reply src/CabalHelper/Compiletime/CompPrograms.hs:97]: oh you are right. I am sorry for this wrong nitpick :/

Comment (jneira) [reply src/CabalHelper/Compiletime/CompPrograms.hs:97]: no problem and please, keep on it :smile_cat:

**Comment by DanielG** [comment]
> ```
> 1) CabalHelper, cabal-helper spec, cradle discovery and loading, dummy filepath, finds none-cradle, stack repo
>        uncaught exception: IOException of type OtherError
>        readCreateProcess: stack "path" "--stack-yaml=D:\\a\\1\\s\\test\\testdata\\cabal-helper\\simple-stack\\stack.yaml" (exit 1): failed
> ```
> 
> Unfortunately the error is not very specific

Seems pretty specific to me: `"(exit 1): failed"`, so the `stack path` call itself failed.

I think you guys really should be capturing stderr for the tests, otherwise that sort of thing is going to remain a mistery. But honestly it's probably quite difficult to do with hspec because of it's parallel test support. I'd use something else for integration tests like this TBH. (If you find a good alternative let me know, I just roll my own ATM :)

File: src/CabalHelper/Compiletime/CompPrograms.hs [hunk 2]
```diff
@@ -92,8 +92,11 @@ patchBuildToolProgs SStack progs = do
...
+    case mb_exe_path of
+      Just exe_path -> createSymbolicLink exe_path (bindir </> takeFileName target)
+      Nothing -> createSymLinkFromCwd
+  | otherwise = createSymLinkFromCwd
+  where createSymLinkFromCwd = do
+          cwd <- getCurrentDirectory
+          createSymbolicLink (cwd </> target) (bindir </> takeFileName target)
```
Comment (DanielG) [inline src/CabalHelper/Compiletime/CompPrograms.hs]: I don't really understand what you're trying to achieve here?

In my mental model `target` should always exist here because we went through `GHC.configure` and consequently `configureProgram`, but I just checked and a program not being found isn't an error for that function. So i suppose what we should do is call `requireProgram` instead of using `getProg` which will throw an error if the program couldn't be found. 

Still how is falling back to guessing the target program is in cwd a good idea here?

Comment (jneira) [reply src/CabalHelper/Compiletime/CompPrograms.hs]: Oh, it does not what i thought. The strange thing is it fixes the error in azure, i suppose it is by accident. 
I'll try to throw an error instead, following your suggestion.

Comment (jneira) [reply src/CabalHelper/Compiletime/CompPrograms.hs]: @DanielG i've change the missing patter case to throw an error, with the info available. I hope at least it could help to find the cause

**Comment by jneira** [comment]
After replacing the missing pattern case with an error i can see the following in azure ci:
```
src\CabalHelper\Compiletime\CompPrograms.hs:98:18: 
  1) CabalHelper, cabal-helper spec, cradle discovery and loading, dummy filepath, finds none-cradle, stack repo
       uncaught exception: ErrorCall
       Error trying to create symlink to haddock: haddock executable not found.
       CallStack (from HasCallStack):
         error, called at src\CabalHelper\Compiletime\CompPrograms.hs:98:18 in cabal-helper-1.0.0.0-8rncFQ8Hkql8OdWNk7I7Bw-c-h-internal:CabalHelper.Compiletime.CompPrograms
```
However it seems being `haddock` the program name it should match
https://github.com/DanielG/cabal-helper/blob/c677e7239c95268175d1ad155c2d40b82eb9887a/src/CabalHelper/Compiletime/CompPrograms.hs#L59-L65

If all the three programs follow that scheme...

So it seems not all follow it but `haddock` does. I wonder if we can simply ignore the programs that has the simple name.

**Comment by jneira** [comment]
With the last commit (87f41cf) the build with stack and ghc-8.6.4 return to green:
https://dev.azure.com/jneira/haskell-ide-engine/_build/results?buildId=612&view=results

File: src/CabalHelper/Compiletime/CompPrograms.hs [hunk 3]
```diff
@@ -80,9 +81,12 @@ patchBuildToolProgs SStack progs = do
...
   withSystemTempDirectory "cabal-helper-symlinks" $ \bindir -> do
-  createProgSymlink bindir $ ghcProgram progs
-  createProgSymlink bindir $ ghcPkgProgram progs
-  createProgSymlink bindir $ haddockProgram progs
+  when (ghcProgram progs /= "ghc") $
+    createProgSymlink bindir $ ghcProgram progs
+  when (ghcPkgProgram progs /= "ghc-pkg") $
+    createProgSymlink bindir $ ghcPkgProgram progs
+  when (haddockProgram progs /= "haddock") $
+    createProgSymlink bindir $ haddockProgram progs
```
Comment (DanielG) [inline src/CabalHelper/Compiletime/CompPrograms.hs]: I'm pretty sure this isn't going to work either. IIRC Stack will search for the ghc related tools in the directory it found ghc. 

So if ghc is unqualified here but the other tools aren't we create the symlink farm but stack will search for ghc, find it on PATH, say in /usr/bin or something and pick up ghc-pkg and haddock from there too instead of the ones the user specified.

Also you're not handling the case where the tools are unqualified but have a version postfix.

**Review by DanielG — CHANGES_REQUESTED** [review]
This smells pretty hacky to me overall, I think you're trying to paper over a symptom not the root cause here.

From some more staring at the existing code I notice two problems:

- I'm using `withSystemTempDirectory` which will remove the tempdir after `patchBuildToolProgs` returns, that can't be right :)
- `GHC.configure` doesn't actually require haddock to be present, that together with your `Error trying to create symlink to haddock: haddock executable not found` error from above makes me think that's probably the real problem we have here.

So instead of deciding whether to create the symlink based on the respective setting being non-default I think you should check if the program was found and skip creating the symlink if not, but only for haddock, since ghc and ghc-pkg are legitimately required (though GHC.configure will already have errored out about that).

**Comment by jneira** [comment]
ok, with 257273c i think i've adressed:

> I think you should check if the program was found and skip creating the symlink if not, but only for haddock, since ghc and ghc-pkg are legitimately required (though GHC.configure will already have errored out about that). 

About:

> I'm using withSystemTempDirectory which will remove the tempdir after patchBuildToolProgs returns, that can't be right :)

and your alternative proposed in irc:

>  I think instead of having the stackEnv field in Programs if we just stick a bool in there that says whether or not to do the symlink farm we can create it when we actually run stack

do you think we could merge the pr as is (the code will be reused in the alternative)?

File: src/CabalHelper/Compiletime/CompPrograms.hs [hunk 4]
```diff
@@ -80,20 +81,23 @@ patchBuildToolProgs SStack progs = do
...
-createProgSymlink bindir target
+createProgSymlink :: Bool -> FilePath -> FilePath -> IO ()
+createProgSymlink required bindir target
   | [exe] <- splitPath target = do
-    Just exe_path <- findExecutable exe
-    createSymbolicLink exe_path (bindir </> takeFileName target)
+    mb_exe_path <- findExecutable exe
+    case mb_exe_path of
+      Just exe_path -> createSymbolicLink exe_path (bindir </> takeFileName target)
+      Nothing -> when required $ error $ "Error trying to create symlink to " ++ target ++ ": "
```
Comment (DanielG) [inline src/CabalHelper/Compiletime/CompPrograms.hs]: You should use our `panicIO` here, just `error` will cause an async exception. Those are particularly nasty to catch and there's no reason to do it in an IO context.

Also put single quotes around the executable name please.

File: src/CabalHelper/Compiletime/CompPrograms.hs [hunk 5]
```diff
@@ -2,6 +2,7 @@
 
 module CabalHelper.Compiletime.CompPrograms where
 
+import Control.Monad (when)
```
Comment (DanielG) [inline src/CabalHelper/Compiletime/CompPrograms.hs:5]: This is unused now.

**Review by DanielG — CHANGES_REQUESTED** [review]

File: src/CabalHelper/Compiletime/CompPrograms.hs (hunk 5 above)
Comment (jneira) [reply src/CabalHelper/Compiletime/CompPrograms.hs:5]: it is still used here: https://github.com/DanielG/cabal-helper/pull/93/files#diff-cdb770e5b44f45493591eb04ed6d7453R99

File: src/CabalHelper/Compiletime/CompPrograms.hs (hunk 4 above)
Comment (jneira) [reply src/CabalHelper/Compiletime/CompPrograms.hs]: done!
